export const redTools = [
  {
    name: "Vulnerability Scanner",
    description: "Scan websites for security weaknesses like XSS or SQL injection.",
    slug: "vuln-scanner",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "Source Code Analyzer",
    description: "Static analysis for Python, Node, Go, and Java codebases.",
    slug: "Source-Code",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "passive",
  },
  // {
  //   name: "Checkmarx Scanner",
  //   description: "Code security review workflow wired to the existing analysis route.",
  //   slug: "codeAnalysis",
  //   buttonLabel: "Launch Tool",
  //   team: "red",
  //   teamLabel: "Red Team",
  //   status: "passive",
  // },
  {
    name: "Subdomain Scanner",
    description: "Enumerate subdomains and analyze their security posture.",
    slug: "subdomainEnumeration",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "passive",
  },
  {
    name: "Website Recon",
    description: "Reconnaissance to identify metadata, DNS, and technologies in use.",
    slug: "webrecon",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "passive",
  },
  {
    name: "Technology Fingerprinter",
    description: "Fingerprint frameworks, CMSs, and front-end infrastructure.",
    slug: "fingerPrint",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "Brute Force Scanner",
    description: "Automated path and endpoint enumeration for exposed assets.",
    slug: "bruteForce",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  // {
  //   name: "Mocha Testing",
  //   description: "Review available Mocha commands, options, and usage patterns.",
  //   slug: "mochaForm",
  //   buttonLabel: "Launch Tool",
  //   team: "red",
  //   teamLabel: "Red Team",
  //   status: "passive",
  // },
  {
    name: "Broken Link Checker",
    description: "Scan pages for dead or broken links and operational drift.",
    slug: "brokenStreamForm",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "passive",
  },
  {
    name: "WordPress Scanner",
    description: "Review plugins, versions, and common WordPress misconfigurations.",
    slug: "wordpressForm",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "API Testing",
    description: "Validate API endpoints, headers, timing, and exposed responses.",
    slug: "apiForm",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "Port Scanner",
    description: "Discover open ports and exposed services.",
    slug: "portScannerForm",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "Clickjacking Tester",
    description: "Check for UI redressing vulnerabilities across pages.",
    slug: "clickjackingTester",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "passive",
  },
  {
    name: "CSRF Scanner",
    description: "Detect CSRF vulnerabilities across forms and token handling.",
    slug: "csrfChecker",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "Open Redirect Tester",
    description: "Find unsafe redirection vulnerabilities in live flows.",
    slug: "openRedirectTester",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "Secret Key Scanner",
    description: "Search repositories and snippets for exposed credentials.",
    slug: "secretKeyScanner",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "passive",
  },
  {
    name: "Session Fixation Tester",
    description: "Detect session fixation weaknesses in application code paths.",
    slug: "sessionFixationChecker",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "Whois Domain Lookup",
    description: "Retrieve domain registration and ownership context.",
    slug: "whoisLookup",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "passive",
  },
  {
    name: "XSS Tester",
    description: "Identify Cross-Site Scripting risks and reflection paths.",
    slug: "xssTester",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "SQLi Scanner",
    description: "Scan websites for SQL Injection weaknesses.",
    slug: "nexpose-scan",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
  {
    name: "Database Security Checker",
    description: "Review database exposure, connectivity, and security posture.",
    slug: "DbSecurityChecker",
    buttonLabel: "Launch Tool",
    team: "red",
    teamLabel: "Red Team",
    status: "active",
  },
];

export const blueTools = [
  {
    name: "WAF Scanner",
    description: "Detect and analyze WAF protection on a website.",
    slug: "firewallDashboard",
    buttonLabel: "Launch Tool",
    team: "blue",
    teamLabel: "Blue Team",
    status: "active",
  },
  {
    name: "HTTPS Security Checker",
    description: "Validate HTTPS posture, redirects, and protective headers.",
    slug: "httpsCheckerForm",
    buttonLabel: "Launch Tool",
    team: "blue",
    teamLabel: "Blue Team",
    status: "passive",
  },
  {
    name: "JWT Signature Validator",
    description: "Ensure JWT signature integrity and algorithm safety.",
    slug: "JWTSignatureValidator",
    buttonLabel: "Launch Tool",
    team: "blue",
    teamLabel: "Blue Team",
    status: "active",
  },
  {
    name: "OAuth Token Analyzer",
    description: "Inspect OAuth tokens for structural and expiry risks.",
    slug: "OAuthTokenInspector",
    buttonLabel: "Launch Tool",
    team: "blue",
    teamLabel: "Blue Team",
    status: "passive",
  },
  {
    name: "Obfuscation Detector",
    description: "Identify obfuscation and suspicious encoding in code.",
    slug: "obfuscationChecker",
    buttonLabel: "Launch Tool",
    team: "blue",
    teamLabel: "Blue Team",
    status: "passive",
  },
  {
    name: "Regex Security Validator",
    description: "Check regular expressions for security flaws.",
    slug: "regexDetector",
    buttonLabel: "Launch Tool",
    team: "blue",
    teamLabel: "Blue Team",
    status: "passive",
  },
  {
    name: "Reverse DNS Resolver",
    description: "Retrieve PTR, geo, and blacklist context for an IP.",
    slug: "reverseDNSLookup",
    buttonLabel: "Launch Tool",
    team: "blue",
    teamLabel: "Blue Team",
    status: "passive",
  },
  {
    name: "MDR Monitor",
    description: "Monitor threat signals and incident response status.",
    slug: "mdr-monitor",
    buttonLabel: "Launch Tool",
    team: "blue",
    teamLabel: "Blue Team",
    status: "active",
  },
];

export const greenTools = [
  {
    name: "Sitemap Generator",
    description: "Generate XML sitemaps for search and visibility hygiene.",
    slug: "sitemapForm",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  {
    name: "Meta Tag Analyzer",
    description: "Analyze title, description, and metadata health.",
    slug: "meta-tag",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  {
    name: "Keyword Density Checker",
    description: "Review keyword frequency and page optimization balance.",
    slug: "keyword-checker",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  {
    name: "Link Detector",
    description: "Detect suspicious, malicious, or unsafe links.",
    slug: "check-link",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "active",
  },
  {
    name: "SecureCrypt",
    description: "Encrypt and decrypt text using strong secure algorithms.",
    slug: "securecrypt",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  {
    name: "File Scanner",
    description: "Scan files for malware or suspicious indicators.",
    slug: "folder-threat-scanner",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "active",
  },
  {
    name: "WhatsApp Privacy Inspector",
    description: "Check WhatsApp settings for practical privacy risks.",
    slug: "whatsapp-privacy-inspector",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  // {
  //   name: "Email Attachment Analyzer",
  //   description: "Review email attachments for risky file indicators.",
  //   slug: "email-attachment-analyzer",
  //   buttonLabel: "Launch Tool",
  //   team: "green",
  //   teamLabel: "Green Team",
  //   status: "passive",
  // },
  {
    name: "IP Address Info Finder",
    description: "Fetch location and network details for an IP address.",
    slug: "ip-address-info-finder",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  {
    name: "QR Tool",
    description: "Review suspicious QR codes and generate new ones.",
    slug: "fake-qr-code-detector",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "active",
  },
  {
    name: "Website Optimization Tool",
    description: "Surface payload and render issues across websites.",
    slug: "website-optimization-tool",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  {
    name: "SEO Score Analyzer Tool",
    description: "Analyze SEO posture and improvement opportunities.",
    slug: "seo-score-analyzer-tool",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  {
    name: "Keyword Generator",
    description: "Generate SEO-friendly keyword suggestions.",
    slug: "KeywordGenerator",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  {
    name: "Data Breach",
    description: "Find where your email, phone number, or username is exposed.",
    slug: "osint",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "active",
  },
  {
    name: "URL Shortener",
    description: "Create short URLs and simple redirect links.",
    slug: "url-shortener",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
  {
    name: "Password Strength Checker",
    description: "Check password strength and estimated resilience.",
    slug: "password-checker",
    buttonLabel: "Launch Tool",
    team: "green",
    teamLabel: "Green Team",
    status: "passive",
  },
];

export const purpleTools = [
  {
    name: "Cyber Fraud Identifier",
    description: "Flags potential online fraud using prior public records.",
    slug: "cyber-fraud-identifier",
    buttonLabel: "Launch Tool",
    team: "purple",
    teamLabel: "Purple Team",
    status: "passive",
  },
];

export const vaTools = [
  {
    name: "Port Scanner",
    description: "Perform a complete network sweep to enumerate open ports and services.",
    slug: "portScannerForm",
    buttonLabel: "Launch Tool",
    team: "va",
    teamLabel: "VA",
    status: "active",
  },
  {
    name: "Basic Network Scanning",
    description: "Check target surfaces for foundational exposure and weak services.",
    slug: "basic-network-scan",
    buttonLabel: "Launch Tool",
    team: "va",
    teamLabel: "VA",
    status: "active",
  },
  {
    name: "Credential Validation",
    description: "Assess access patterns and exposed identity attack paths.",
    slug: "cloud-security",
    buttonLabel: "Launch Tool",
    team: "va",
    teamLabel: "VA",
    status: "passive",
  },
  {
    name: "Advance Scanning",
    description: "Analyze systems and services for deeper configuration issues.",
    slug: "system-hardening",
    buttonLabel: "Launch Tool",
    team: "va",
    teamLabel: "VA",
    status: "passive",
  },
  {
    name: "Advanced Dynamic Scan",
    description: "Search applications for exposed secrets and live weaknesses.",
    slug: "secret-key-scanner",
    buttonLabel: "Launch Tool",
    team: "va",
    teamLabel: "VA",
    status: "passive",
  },
  {
    name: "Malwave Scan",
    description: "Review dependencies, packages, and malicious package risk.",
    slug: "dependency-check",
    buttonLabel: "Launch Tool",
    team: "va",
    teamLabel: "VA",
    status: "passive",
  },
  {
    name: "Web Application Test",
    description: "Review app and server configuration issues, headers, and cookies.",
    slug: "web-app-audit",
    buttonLabel: "Launch Tool",
    team: "va",
    teamLabel: "VA",
    status: "passive",
  },
  {
    name: "Active Directory Scan",
    description: "Generate consolidated findings and remediation paths.",
    slug: "active-directory-scan",
    buttonLabel: "Launch Tool",
    team: "va",
    teamLabel: "VA",
    status: "passive",
  },

  {
    name: "Credential Path Audit",
    description: "Trace identity pathways and privilege escalation routes.",
    slug: "credential-path-audit",
    buttonLabel: "Launch Tool",
    team: "va",
    teamLabel: "VA",
    status: "passive",
  },

];

export const toolGroups = [
  { key: "red", label: "Red Team", count: redTools.length, tools: redTools },
  { key: "blue", label: "Blue Team", count: blueTools.length, tools: blueTools },
  { key: "green", label: "Green Team", count: greenTools.length, tools: greenTools },
  { key: "purple", label: "Purple Team", count: purpleTools.length, tools: purpleTools },
  { key: "va", label: "VA", count: vaTools.length, tools: vaTools },
];
